name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pre
      run: mkdir build
    - name: make
      run: cmake --build build
    - name: after
      run: rm -rf build
